import test from "node:test";
import assert from "node:assert/strict";
import vm from "node:vm";
import { buildReleaseBootstrap } from "../scripts/prepare-release-layout.mjs";
const meta={id:"build-new",sha:"abcdef123",shortSha:"abcdef1",builtAt:"2026-07-18T00:00:00.000Z",appPath:"/Haiku-Cosmos/builds/build-new/index.html",assetBase:"/Haiku-Cosmos/builds/build-new/",integrityPath:"/Haiku-Cosmos/builds/build-new/build-integrity.json"};
const manifest=[{kind:"style",href:"assets/app.css"},{kind:"script",type:"classic",src:"runtime/a.js"},{kind:"script",type:"module",src:"hc.three_module_bridge.js"},{kind:"script",type:"classic",src:"runtime/b.js"}];
function storage(initial={}){const m=new Map(Object.entries(initial));return{get length(){return m.size},key:i=>Array.from(m.keys())[i]??null,getItem:k=>m.get(k)??null,setItem:(k,v)=>m.set(k,String(v)),removeItem:k=>m.delete(k),entries:()=>Object.fromEntries(m)}}
async function run(local={}){const code=buildReleaseBootstrap(manifest).match(/<script data-hc-release-bootstrap>([\s\S]*?)<\/script>/)[1],loaded=[],s=storage(local);const context={window:{},console,Promise,Error,JSON,localStorage:s,sessionStorage:storage(),document:{getElementById:()=>({hidden:false}),querySelector:()=>({textContent:JSON.stringify(manifest)}),createElement:()=>({}),head:{appendChild:e=>{loaded.push(e.href||e.src);setTimeout(()=>e.onload(),0)}}}};context.window={...context,HC_BUILD_INFO:meta};vm.createContext(context);vm.runInContext(code,context);await new Promise(r=>setTimeout(r,35));return{loaded,local:s.entries(),boot:context.window.HC_RELEASE_BOOTSTRAP}}
test("immutable app loads ordered manifest only from its assetBase",async()=>{const r=await run({"hc:release-build-id":"build-new"});assert.deepEqual(r.loaded,["/Haiku-Cosmos/builds/build-new/assets/app.css","/Haiku-Cosmos/builds/build-new/runtime/a.js","/Haiku-Cosmos/builds/build-new/hc.three_module_bridge.js","/Haiku-Cosmos/builds/build-new/runtime/b.js"]);assert.equal(r.boot.buildId,"build-new")});
test("build change resets only Haiku Cosmos keys",async()=>{const r=await run({"hc:old":"1",other:"stay"});assert.equal(r.local.other,"stay");assert.equal(r.local["hc:release-build-id"],"build-new");assert.equal(r.boot.storageResetPerformed,true)});
